dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master  
notifications:
  email:
    recipients:
      - deepesh@ost.com      
    on_success: always
    on_failure: always
node_js:
  - "8"  
services:
  - rabbitmq  
before_install:
  - "amqp://guest: guest@127.0.0.1:5672/?heartbeat=30"  
install: 
  
before_script:  
  
script:  
  
after_script:
  
  
